import {
  Building2,
  Factory,
  GraduationCap,
  Landmark,
  Lightbulb,
  Rocket,
  Sparkles,
  TrendingUp,
  Users,
  Building,
} from "lucide-react";
import type { NodeData } from "../components/sections/landingPage/Herosection/EcosystemNode";
import ccctLogo from "@/shared/assets/ccct.png";
import attcLogo from "@/shared/assets/attc.png";
import deptLogo from "@/shared/assets/commerce-industries-dept.png";
import inspiresLogo from "@/shared/assets/sikkim-inspires.png";
import iimLogo from "@/shared/assets/iim-calcutta-innovation-park.png";

export const NODES_DATA: NodeData[] = [
  {
    id: 1,
    title: "Startups",
    subtitle: "1,284 registered",
    icon: Rocket,
    position: { left: "52%", top: "7%" },
    borderColor: "#ED6A5F",
    iconBg: "#FDECEA",
    iconColor: "#C64A3F",
    floatDuration: "4.9s",
    animationDelay: "0.50s",
  },
  {
    id: 2,
    title: "Investors",
    subtitle: "28 on the panel",
    icon: TrendingUp,
    position: { left: "73.51%", top: "20.60%" },
    borderColor: "#2EB67D",
    iconBg: "#E6F7EF",
    iconColor: "#22946A",
    floatDuration: "5.2s",
    animationDelay: "1.00s",
  },
  {
    id: 3,
    title: "Mentors",
    subtitle: "142 empanelled",
    icon: Users,
    position: { left: "86.03%", top: "43.34%" },
    borderColor: "#36C5F0",
    iconBg: "#E3F7FE",
    iconColor: "#1093C4",
    floatDuration: "5.4s",
    animationDelay: "1.50s",
  },
  {
    id: 4,
    title: "Incubation centres",
    subtitle: "9 across districts",
    icon: Building2,
    position: { left: "81.68%", top: "69.19%" },
    borderColor: "#8A5090",
    iconBg: "#F8F1F9",
    iconColor: "#4A154B",
    floatDuration: "5.7s",
    animationDelay: "2.00s",
  },
  {
    id: 5,
    title: "Innovation hubs",
    subtitle: "4 sector hubs",
    icon: Lightbulb,
    position: { left: "76%", top: "86.06%" },
    borderColor: "#ECB22E",
    iconBg: "#FDF4DE",
    iconColor: "#B4841B",
    floatDuration: "6.0s",
    animationDelay: "2.50s",
  },
  {
    id: 6,
    title: "Academia",
    subtitle: "17 partner colleges",
    icon: GraduationCap,
    position: { left: "37.49%", top: "86.06%" },
    borderColor: "#1093C4",
    iconBg: "#E3F7FE",
    iconColor: "#0B6E93",
    floatDuration: "6.3s",
    animationDelay: "3.00s",
  },
  {
    id: 7,
    title: "Enterprises",
    subtitle: "MSMEs & industry",
    icon: Factory,
    position: { left: "18.32%", top: "69.19%" },
    borderColor: "#8B8379",
    iconBg: "#F6F2EC",
    iconColor: "#423E39",
    floatDuration: "6.6s",
    animationDelay: "3.50s",
  },
  {
    id: 8,
    title: "Innovators",
    subtitle: "idea-stage founders",
    icon: Sparkles,
    position: { left: "13.97%", top: "43.34%" },
    borderColor: "#B084B4",
    iconBg: "#EEE1F0",
    iconColor: "#6B2D6F",
    floatDuration: "6.8s",
    animationDelay: "4.00s",
  },
  {
    id: 9,
    title: "Commerce & Industries",
    subtitle: "Government of Sikkim",
    icon: Landmark,
    position: { left: "26.49%", top: "20.60%" },
    borderColor: "#6B2D6F",
    iconBg: "#EEE1F0",
    iconColor: "#2E0C2F",
    floatDuration: "7.1s",
    animationDelay: "4.50s",
  },
];

export const STARTUP_DATA = (t: any) => [
  {
    key: "dic-gtk",
    name: t("startups.dicGtk.name", "DIC Gangtok"),
    town: t("startups.dicGtk.town", "Gangtok, Gangtok district"),
    lon: 88.6138,
    lat: 27.3314,
    color: "#ED6A5F",
    side: "right",
    label: t("startups.dicGtk.label", "DIC Gangtok"),
    dy: -9,
    icon: Landmark,
    pos: { left: "60.0%", top: "2.8%", rot: 1.5 },
  },
  {
    key: "hub-gtk",
    name: t("startups.hubGtk.name", "Innovation Hub"),
    town: t("startups.hubGtk.town", "Gangtok"),
    lon: 88.606,
    lat: 27.318,
    color: "#B084B4",
    side: "right",
    label: t("startups.hubGtk.label", "Innovation Hub"),
    dy: 14,
    small: true,
    icon: Lightbulb,
    pos: { left: "81.4%", top: "25.9%", rot: -1.5 },
  },
  {
    key: "dic-pky",
    name: t("startups.dicPky.name", "DIC Pakyong"),
    town: t("startups.dicPky.town", "Pakyong, Pakyong district"),
    lon: 88.59,
    lat: 27.2333,
    color: "#6B2D6F",
    side: "right",
    label: t("startups.dicPky.label", "Pakyong"),
    icon: Landmark,
    pos: { left: "81.4%", top: "58.6%", rot: 1.5 },
  },
  {
    key: "attc",
    name: t("startups.attc.name", "Incubation Centre"),
    town: t("startups.attc.town", "ATTC Bardang, near Singtam"),
    lon: 88.503,
    lat: 27.247,
    color: "#1093C4",
    side: "right",
    label: t("startups.attc.label", "ATTC Bardang"),
    icon: Building,
    pos: { left: "60.0%", top: "81.8%", rot: -1.5 },
  },
  {
    key: "dic-gys",
    name: t("startups.dicGys.name", "DIC Gyalshing"),
    town: t("startups.dicGys.town", "Gyalshing, Gyalshing district"),
    lon: 88.2667,
    lat: 27.2833,
    color: "#36C5F0",
    side: "left",
    label: t("startups.dicGys.label", "DIC Gyalshing"),
    icon: Landmark,
    pos: { left: "29.7%", top: "2.8%", rot: -1.5 },
  },
  {
    key: "dic-srg",
    name: t("startups.dicSrg.name", "DIC Soreng"),
    town: t("startups.dicSrg.town", "Soreng, Soreng district"),
    lon: 88.16,
    lat: 27.16,
    color: "#2EB67D",
    side: "left",
    label: t("startups.dicSrg.label", "DIC Soreng"),
    icon: Landmark,
    pos: { left: "8.3%", top: "25.9%", rot: 1.5 },
  },
  {
    key: "dic-nam",
    name: t("startups.dicNam.name", "DIC Namchi"),
    town: t("startups.dicNam.town", "Namchi, Namchi district"),
    lon: 88.3637,
    lat: 27.1675,
    color: "#F2B651",
    side: "left",
    label: t("startups.dicNam.label", "DIC Namchi"),
    icon: Landmark,
    pos: { left: "8.3%", top: "58.6%", rot: -1.5 },
  },
  {
    key: "ccct",
    name: t("startups.ccct.name", "Incubation Centre"),
    town: t("startups.ccct.town", "CCCT Chisopani, South Sikkim"),
    lon: 88.42,
    lat: 27.145,
    color: "#E01E5A",
    side: "left",
    label: t("startups.ccct.label", "CCCT Chisopani"),
    icon: Building,
    pos: { left: "29.7%", top: "81.8%", rot: 1.5 },
  },
];

export const SECTOR_DATA = (t: any) => [
  {
    name: t("sectors.ccct.name", "CCCT Chisopani"),
    count: t("sectors.incubation", "Incubation centre"),
    color: "#2E3192",
    logo: ccctLogo,
  },
  {
    name: t("sectors.attc.name", "ATTC Bardang"),
    count: t("sectors.incubation", "Incubation centre"),
    color: "#B4841B",
    logo: attcLogo,
  },
  {
    name: t("sectors.dept.name", "Commerce & Industries Dept."),
    count: t("sectors.govt", "Government of Sikkim"),
    color: "#4A154B",
    logo: deptLogo,
  },
  {
    name: t("sectors.inspires.name", "Sikkim Inspires"),
    count: t("sectors.empower", "Employ · Empower · Enable"),
    color: "#ED6A5F",
    logo: inspiresLogo,
  },
  {
    name: t("sectors.iim.name", "IIM Calcutta Innovation Park"),
    count: t("sectors.partner", "Incubation partner"),
    color: "#1093C4",
    logo: iimLogo,
  },
];
