import {
  Building2,
  Factory,
  GraduationCap,
  Landmark,
  Lightbulb,
  Rocket,
  Sparkles,
  TrendingUp,
  Users,
} from "lucide-react";
import type { NodeData } from "../components/sections/landingPage/Herosection/EcosystemNode";

export const NODES_DATA: NodeData[] = [
  {
    id: 1,
    title: "Startups",
    subtitle: "1,284 registered",
    icon: Rocket,
    position: { left: "52%", top: "7%" },
    borderColor: "#ED6A5F",
    iconBg: "#FDECEA",
    iconColor: "#C64A3F",
    floatDuration: "4.9s",
    animationDelay: "0.50s",
  },
  {
    id: 2,
    title: "Investors",
    subtitle: "28 on the panel",
    icon: TrendingUp,
    position: { left: "73.51%", top: "20.60%" },
    borderColor: "#2EB67D",
    iconBg: "#E6F7EF",
    iconColor: "#22946A",
    floatDuration: "5.2s",
    animationDelay: "1.00s",
  },
  {
    id: 3,
    title: "Mentors",
    subtitle: "142 empanelled",
    icon: Users,
    position: { left: "86.03%", top: "43.34%" },
    borderColor: "#36C5F0",
    iconBg: "#E3F7FE",
    iconColor: "#1093C4",
    floatDuration: "5.4s",
    animationDelay: "1.50s",
  },
  {
    id: 4,
    title: "Incubation centres",
    subtitle: "9 across districts",
    icon: Building2,
    position: { left: "81.68%", top: "69.19%" },
    borderColor: "#8A5090",
    iconBg: "#F8F1F9",
    iconColor: "#4A154B",
    floatDuration: "5.7s",
    animationDelay: "2.00s",
  },
  {
    id: 5,
    title: "Innovation hubs",
    subtitle: "4 sector hubs",
    icon: Lightbulb,
    position: { left: "76%", top: "86.06%" },
    borderColor: "#ECB22E",
    iconBg: "#FDF4DE",
    iconColor: "#B4841B",
    floatDuration: "6.0s",
    animationDelay: "2.50s",
  },
  {
    id: 6,
    title: "Academia",
    subtitle: "17 partner colleges",
    icon: GraduationCap,
    position: { left: "37.49%", top: "86.06%" },
    borderColor: "#1093C4",
    iconBg: "#E3F7FE",
    iconColor: "#0B6E93",
    floatDuration: "6.3s",
    animationDelay: "3.00s",
  },
  {
    id: 7,
    title: "Enterprises",
    subtitle: "MSMEs & industry",
    icon: Factory,
    position: { left: "18.32%", top: "69.19%" },
    borderColor: "#8B8379",
    iconBg: "#F6F2EC",
    iconColor: "#423E39",
    floatDuration: "6.6s",
    animationDelay: "3.50s",
  },
  {
    id: 8,
    title: "Innovators",
    subtitle: "idea-stage founders",
    icon: Sparkles,
    position: { left: "13.97%", top: "43.34%" },
    borderColor: "#B084B4",
    iconBg: "#EEE1F0",
    iconColor: "#6B2D6F",
    floatDuration: "6.8s",
    animationDelay: "4.00s",
  },
  {
    id: 9,
    title: "Commerce & Industries",
    subtitle: "Government of Sikkim",
    icon: Landmark,
    position: { left: "26.49%", top: "20.60%" },
    borderColor: "#6B2D6F",
    iconBg: "#EEE1F0",
    iconColor: "#2E0C2F",
    floatDuration: "7.1s",
    animationDelay: "4.50s",
  },
];

export const RegistrationHeaderConfig = {
  startup: {
    badge: "Startup Path",
    title: "Register your Startup",
    subtitle:
      "Tell us about your venture to unlock funding, incubation, and growth.",
    icon: Rocket,
    iconBg: "#FDECEA",
    iconColor: "#C64A3F",
  },
  enterprise: {
    badge: "Enterprise Portal",
    title: "Enterprise Onboarding",
    subtitle: "Partner with us to discover and scale innovative solutions.",
    icon: Building2,
    iconBg: "#F6F2EC",
    iconColor: "#423E39",
  },
  aspirant: {
    badge: "Aspirant Journey",
    title: "Begin Your Journey",
    subtitle:
      "Got an idea? Take the first step towards your entrepreneurial dream.",
    icon: Lightbulb,
    iconBg: "#E6F7EF",
    iconColor: "#22946A",
  },
  mentor: {
    badge: "Mentor Network",
    title: "Join as a Mentor",
    subtitle: "Share your expertise and guide the next generation of founders.",
    icon: GraduationCap,
    iconBg: "#EEE1F0",
    iconColor: "#6B2D6F",
  },
  // Fallback for edge cases
  default: {
    badge: "Registration",
    title: "Create your Account",
    subtitle: "Fast, simple, and guided application process.",
    icon: Rocket,
    iconBg: "bg-gray-100",
    iconColor: "text-gray-600",
  },
};
